### ISSUE TITLE
🤔 Add a "Help" button

### ISSUE THREAD

**Issue by LyubomirT** [LyubomirT/wincuts#5]
Many users won't go deep diving trying to find the repository's README; a simple Help button should work way better.

**Comment by LyubomirT** [comment]
Just a note: I'm looking to add the help button in the desktop application specifically and not the download page.

**Comment by wy8933** [comment]
Hi, I will like to pick up what [GAURAV142004](https://github.com/GAURAV142004) have woked on, and add the help button into the app

**Comment by LyubomirT** [comment]
I appreciate the continued support @wy8933! Assigned you to the issue, good luck!

**Comment by LyubomirT** [comment]
Implemented by @wy8933!
